### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by ndmitchell** [andrewhickman/fs-err#24]
Looking at `std::fs`, for the functions I was using in my project, I was missing `hard_link`, `soft_link`, `rename`. Could these be added?

**Comment by andrewhickman** [comment]
`soft_link` is deprecated. Would your use case be solved by exposing the platform specific replacements (`std::os::unix::fs::symlink` and `std::os::windows::fs::{symlink_file, symlink_dir}`) instead?

**Comment by ndmitchell** [comment]
I'd have been happy without soft_link, given its deprecated - but thanks for the inclusion anyway!
