### ISSUE TITLE
Provide a `fn file_mut(&mut self) -> &mut std::fs::File`

### ISSUE THREAD

**Issue by drahnr** [andrewhickman/fs-err#35]
Currently there is no API that allows mutable access to some of those files or conversion to the inner `std::fs::File`. As such one has to go via the os-specific `{FromInto}RawFd` to gain access to the underlying file.

This is required for i.e. the `tar` crate.

**Comment by andrewhickman** [comment]
Would an API like `fn into_parts(self) -> (std::fs::File, PathBuf)` work?

A method returning a mutable reference like `fn file_mut(&mut self) -> &mut std::fs::File` sounds reasonable too, but I didn't think an `&mut std::fs::File` was any more useful than `&std::fs::File`

**Comment by drahnr** [comment]
I was surprised to see the `&mut std::fs::File` in the API as well.

Either works, so since both are very trivial close-to-nop impl I would argue for adding both, `into_parts` seems more versatile since a `fs_err::File` can be re-constructed from those.

**Comment by andrewhickman** [comment]
I've published version [2.6.0](https://crates.io/crates/fs-err/2.6.0) with cd8131d878c529530953f016678790f468787bf7 which adds both methods
