### ISSUE TITLE
Add support for `tokio::fs`

### ISSUE THREAD

**Issue by Veetaha** [andrewhickman/fs-err#36]
The project is very cool for applications that can tolerate synchronous filesystem interaction!
However, if one needs `async` io, `fs_err` can't help with this too much.
As a workaround some operations could be wrapped in `tokio::task::spawn_blocking()`, but it would be better to have a native wrapper for [`tokio::fs`](https://docs.rs/tokio/1.8.1/tokio/fs/index.html) module.

It may be reasonable to have this with a `tokio` cargo feature.

**Comment by andrewhickman** [comment]
Sounds reasonable, I'd accept a PR that implements this.
