### ISSUE TITLE
fs::read_dir API

### ISSUE THREAD

**Issue by LPGhatguy** [andrewhickman/fs-err#4]
It would be useful to expose the `read_dir` function, along with the associated structs `ReadDir` (an iterator) and `DirEntry`.

I have implementations of these in my old FS abstraction (that was the source of #2) that I can tidy up and PR for this crate!

**Comment by andrewhickman** [comment]
I actually need this for my current project, so a PR would be great. Otherwise I'll definitely add this at some point
