### ISSUE TITLE
Add support for path associated functions such as `try_exist` 

### ISSUE THREAD

**Issue by schneems** [andrewhickman/fs-err#46]
Thank you for your work. My team works with the file system heavily, and we need good error messages that include the path being referenced, and your library is helpful in providing this out of the box. 

One thing we've found is that while checking if a file exists or not on the path, it can be confusing to raise an error that says "This file {} does not exist" when the end user can see it on the path but `Path::exists()` returned false because there was an error with permissions (or something else).

Currently, I have some code like this:

```
    if path
        .try_exists()
        .map_err(|error| CustomError::CannotRead(path.clone(), error))?
    {
        Ok(path)
    } else {
        Err(CustomError::DoesNotExist(path))
    }
```

If fs-err supported these operations, then this would be simplified to just `path.try_exists()?`.

The challenge is how to present this as an API. Maybe something like `FsErrPath::try_exists(&path)`?

I would like to make "doing the right thing" for error ergonomics as easy as possible. What you've got is a great start. Would you consider adding some additional io operations to your library?

**Comment by andrewhickman** [comment]
That sounds like a great idea. There are already some wrappers for PathExt [here](https://docs.rs/fs-err/latest/fs_err/trait.PathExt.html), named with the `fs_err_` prefix to avoid ambiguitity. I'd gladly accept a PR to add `fs_err_try_exists`
