### ISSUE TITLE
Display does not include source

### ISSUE THREAD

**Issue by brooksprumo** [andrewhickman/fs-err#51]
When printing out the errors generated by fs-err with *Display*, the message does not contain the source. This often means we know *what* happened, but not *why* an error happened.

For example, I encountered this when a call to `fs_err::hard_link()` failed. I have an error hierarchy that wraps the error from the hard link call. Printing the error with Display shows my custom text, then the text from fs-err, but *not* the text from the source/underlying std::io::Error.

Here's an example in the Playground (please pardon the unpolished nature of the code):
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a5e0844e243ec0807372b01227419b50

The Display1 shows wrapping a normal std::io::Error. We can see the output does not include the path. So this has the *why*, but no *what*.

In Display2, which is what fs-err does, we have the path, but not the underlying source io::Error included in the output. This is having the *what* without the *why*

And Display3 is what I was hoping that fs-err did: it prints the *what* followed by the *why*.

By adding the source at the end of the Display, this automatically keeps printing more and more inner source errors at the end; providing more and more information/context.

For fs-err, this can be accomplished by changing the implementation of Display from here: https://github.com/andrewhickman/fs-err/blob/ba9888793c517a82499c8df1ad013529d8578777/src/errors.rs#L65-L101

To something like:
```patch
    fn fmt(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        use ErrorKind::*;

        let path = self.path.display();

        match self.kind {
-            OpenFile => write!(formatter, "failed to open file `{}`", path),
+            OpenFile => write!(formatter, "failed to open file `{}`: {}", path, self.source),
            // and the same thing for the subsequent arms
```

I can create a PR for this; just wanted to check if this would be well-received first. Please also let me know if there is more information that would be helpful.

Edit: I created a PR since it was quite quick: https://github.com/andrewhickman/fs-err/pull/53

**Comment by andrewhickman** [comment]
There's no clear consensus on which way is better in https://github.com/rust-lang/project-error-handling/issues/23, however I tend to agree with this guideline

> For now, the recommendation is to always do one or the other. If you're going to print your sources, you should not return them via the source function and vice versa.

I think its useful for this crate to expose the original error through `source()`, in case people want to get things like [`raw_os_error`](https://doc.rust-lang.org/stable/std/io/struct.Error.html#method.raw_os_error), so it shouldn't duplicate the error message in the `Display` impl.
