### ISSUE TITLE
Marketing/public docs

### ISSUE THREAD

**Issue by LPGhatguy** [andrewhickman/fs-err#6]
This crate fills an important hole in the ecosystem and that a lot of people would use it if they knew about it and its benefits.

I'd like to help draft an expanded README along with crate-level documentation and examples. I want to make sure my understanding of fs-err's role matches yours, though.

Key points would be:
- fs-err is a (mostly) drop-in replacement for `std::fs`, so it could be used like `use fs_err as fs` to get existing code working
- We should have clear comparisons of error messages between `std::fs` and fs-err
- The crate's scope is the same as `std::fs`, plus methods to expose paths where we've added them
- There might be a path for merging some of the work in this crate back into std (?)

**Comment by andrewhickman** [comment]
I pretty much agree with all of your key points 👍

Apparently at one point `std` did include path information in errors but it was removed
https://internals.rust-lang.org/t/add-filename-information-to-io-error/5120
